baseurl = "/"
title = "Klimawatch"
author = "Code for Germany"
enableRobotsTXT = true
defaultContentLanguage = "de"
language = "de-de"
paginate = 3

theme = "piercer"

[privacy]
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false

[params]
    description = "Wie siehts aus mit Klimaschutz in meiner Kommune?"
    favicon = "/img/favicon.ico"
    logo = "/img/klimawatch_gruen.png"

[params.postcss]
    postcss = false

[params.palette]
    text = "#545454" # was: "#fdfdfd"
    header_text = "white"
    header_border_bottom_color = "#55586b"
    background = "#FFFFFF" # was: "#282a36"
    accent = "#01873B" # was :"#44475a"
    foreground = "#000000" #was: "#f8f8f2"
    separator = "#6272a4"
    cyan = "#8be9fd"
    green = "#50fa7b"
    orange = "#ffb86c"
    pink = "#00441b" # was: "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    yellow = "#f1fa8c"
    footer_text = "#d9d9d9"

[params.fontsizes]
    base = "1em"
    p = "1.25em"
    h4 = "1.563em"
    h3 = "1.953em"
    h2 = "2.441em"
    h1 = "3.052em"

[params.googlefonts]
    font = "Open Sans:400,800"

[params.serviceWorker]
    enable = false

[params.header]
    show = true

[params.cta]
    show = true
    message = "Zeig mir meine Kommune!"
    link = "kommunen/liste/"

[params.fa]
    disable = false
    kit = ""

[params.form]
    show = false
    netlify = false
    action = ""
    method = "POST"
    section = "Contact me!"
    disclaimer = "Elit anim sit labore tempor exercitation in ad cupidatat."
    inputNameName = "Name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your Name"
    inputEmailName = "Email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your Email"
    SubmitValue = ""

[params.contact]
    show = false
    email = "example@hugo.com"
    #phone = "123456789+"
    #skype = "live:example"
    #address = "P. Sherman 42, Wallaby Way, Sydney"

[params.date]
    format = ""

[params.social]
    twitter = "#"
    facebook = "#"
    github = "#"
    gitlab = "#"
    codepen = "#"
    instagram = "#"
    pinterest = "#"
    youtube = "#"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""
    rss = "#"

[params.footer]
    [[params.footer.partners]]
        name = "Code for Germany"
        image_url = "/img/CFG_logo.svg"
        link = "https://codefor.de/"
    [[params.footer.partners]]
        name = "Open Knowledge Foundation Deutschland e.V."
        image_url = "/img/OKF_logo.svg"
        link = "https://okfn.de/"

[params.agreement]
    message = "<a href =\"https://codeformuenster.org/impressum/#impressum\">Impressum</a> &amp; <a href=\"https://codeformuenster.org/impressum/#datenschutz\">Datenschutzerkl√§rung</a>"

[params.copy]
    message = "Klimawatch ist freie Software und lizenziert unter der (TODO: welche Lizenz?!).<br /><a href=\"https://github.com/codeformuenster.org/klimawatch\">Hier lang zum Quelltext.</a>"

[params.notfound]
    message = ""
